const smartPhonicsWordBank = {
  level1: {
    unit1: {
      targetSound: "ABC",
      words: ["A", "a", "B", "b", "C", "c"],
      extraWords: ["Aa", "Bb", "Cc"],
    },
    unit2: {
      targetSound: "DEF",
      words: ["D", "d", "E", "e", "F", "f"],
      extraWords: ["Dd", "Ee", "Ff"],
    },
    unit3: {
      targetSound: "GHI",
      words: ["G", "g", "H", "h", "I", "i"],
      extraWords: ["Gg", "Hh", "Ii"],
    },
    unit4: {
      targetSound: "JKL",
      words: ["J", "j", "K", "k", "L", "l"],
      extraWords: ["Jj", "Kk", "Ll"],
    },
    unit5: {
      targetSound: "MNO",
      words: ["M", "m", "N", "n", "O", "o"],
      extraWords: ["Mm", "Nn", "Oo"],
    },
    unit6: {
      targetSound: "PQR",
      words: ["P", "p", "Q", "q", "R", "r"],
      extraWords: ["Pp", "Qq", "Rr"],
    },
    unit7: {
      targetSound: "STUV",
      words: ["S", "s", "T", "t", "U", "u", "V", "v"],
      extraWords: ["Ss", "Tt", "Uu", "Vv"],
    },
    unit8: {
      targetSound: "WXYZ",
      words: ["W", "w", "X", "x", "Y", "y", "Z", "z"],
      extraWords: ["Ww", "Xx", "Yy", "Zz"],
    },
  },
  level2: {
    unit1: {
      targetSound: "Short Vowel a",
      words: ["dam", "ham", "jam", "ram", "cap", "lap", "map", "nap"],
      extraWords: [
        // -am words
        "bam",
        "cam",
        "fam",
        "gam",
        "sam",

        // -ap words
        "tap",
        "zap",
        "gap",
        "rap",
        "sap",

        // Other -a words with different endings
        "bad",
        "bag",
        "gas",
        "cab",
        "dad",
        "sad",
        "tag",
        "wag",
        "max",
        "pad",
        "rad",
        "sag",
        "fab",
        "lab",
        "ban",
      ],
    },
    unit2: {
      targetSound: "Short Vowel a",
      words: ["can", "fan", "man", "pan", "bat", "cat", "hat", "mat"],
      extraWords: [
        // -an words
        "ban",
        "dan",
        "ran",
        "tan",
        "van",

        // -at words
        "sat",
        "rat",
        "pat",
        "fat",
        "lat",

        // Other short 'a' words
        "bad",
        "gab",
        "bag",
        "sad",
        "wag",
        "pad",
        "rag",
        "dad",
        "sag",
        "gas",
        "lab",
        "cab",
        "mad",
        "nag",
        "tag",
      ],
    },
    unit3: {
      targetSound: "Short Vowel e",
      words: ["jet", "net", "vet", "wet", "bed", "red", "hen", "pen"],
      extraWords: [
        // -et words
        "bet",
        "get",
        "let",
        "met",
        "set",

        // -ed words
        "fed",
        "led",
        "wed",
        "Ted",
        "med",

        // Other short 'e' words
        "leg",
        "peg",
        "beg",
        "den",
        "men",
        "ten",
        "yes",
        "web",
        "rem",
        "hex",
        "gel",
        "hem",
        "gem",
        "bel",
      ],
    },
    unit4: {
      targetSound: "Short Vowel i",
      words: ["bib", "rib", "kid", "lid", "pig", "wig", "fin", "pin"],
      extraWords: [
        // -ib words
        "fib",
        "lib",
        "gib",

        // -id words
        "bid",
        "did",
        "mid",

        // Other short 'i' words
        "big",
        "dig",
        "fig",
        "rig",
        "jig",
        "gin",
        "win",
        "sin",
        "tin",
        "bin",
        "tip",
        "dip",
        "sip",
        "zip",
        "rip",
      ],
    },
    unit5: {
      targetSound: "Short Vowel i",
      words: ["dip", "hip", "lip", "rip", "hit", "sit", "mix", "six"],
      extraWords: [
        // -ip words
        "tip",
        "nip",
        "sip",

        // -it words
        "pit",
        "bit",
        "fit",

        // Other short 'i' words
        "wig",
        "pig",
        "dig",
        "rig",
        "gig",
        "lid",
        "rid",
        "kid",
        "did",
        "bid",
        "pin",
        "sin",
        "tin",
        "win",
        "gin",
      ],
    },
    unit6: {
      targetSound: "Short Vowel o",
      words: ["hot", "pot", "box", "fox", "cop", "hop", "dog", "log"],
      extraWords: [
        // -ot words
        "dot",
        "got",
        "lot",
        "cot",
        "tot",

        // -op words
        "bop",
        "mop",
        "top",
        "hop",
        "pop",

        // Other short 'o' words
        "bog",
        "fog",
        "jog",
        "hog",
        "dog",
        "mob",
        "rob",
        "sob",
        "cod",
        "pod",
        "nod",
        "odd",
        "bob",
        "job",
        "god",
      ],
    },
    unit7: {
      targetSound: "Short Vowel u",
      words: ["bug", "hug", "mug", "rug", "rub", "tub", "cup", "pup"],
      extraWords: [
        // -ug words
        "dug",
        "lug",
        "tug",
        "jug",
        "zug",

        // -ub words
        "cub",
        "hub",
        "sub",
        "nub",

        // Other short 'u' words
        "fun",
        "run",
        "sun",
        "gun",
        "bun",
        "cut",
        "nut",
        "put",
        "gut",
        "hut",
        "mud",
        "sud",
        "bud",
        "dud",
        "lud",
      ],
    },
    unit8: {
      targetSound: "Short Vowel u",
      words: ["bun", "fun", "run", "sun", "bud", "mud", "cut", "nut"],
      extraWords: [
        // -un words
        "gun",
        "hun",
        "pun",
        "nun",
        "tun",

        // -ud words
        "cud",
        "sud",
        "dud",
        "fud",

        // Other short 'u' words
        "bug",
        "dug",
        "hug",
        "lug",
        "mug",
        "cup",
        "pup",
        "tup",
        "sup",
        "rub",
        "tub",
        "hub",
        "rug",
        "jug",
        "nug",
      ],
    },
  },
  level3: {
    unit1: {
      targetSound: "Long Vowel a",
      words: ["bake", "cake", "lake", "rake", "cape", "tape", "cave", "wave"],
      extraWords: [
        // -ake words
        "make",
        "take",
        "bake",
        "wake",
        "sake",

        // -ave words
        "save",
        "gave",
        "wave",
        "rave",
        "pave",

        // Other long 'a' words
        "late",
        "gate",
        "mane",
        "pale",
        "sale",
        "tale",
        "lace",
        "dare",
        "care",
        "hale",
        "male",
        "fade",
        "race",
        "pace",
      ],
    },
    unit2: {
      targetSound: "Long Vowel a",
      words: ["game", "name", "date", "gate", "cane", "mane", "case", "vase"],
      extraWords: [
        // -ame words
        "fame",
        "tame",
        "came",
        "same",
        "lame",

        // -ate words
        "hate",
        "rate",
        "mate",
        "fate",
        "sate",

        // Other long 'a' words
        "lane",
        "care",
        "daze",
        "gaze",
        "haze",
        "pale",
        "tale",
        "sale",
        "male",
        "dare",
        "mare",
        "sane",
        "cage",
        "page",
      ],
    },
    unit3: {
      targetSound: "Long Vowel i",
      words: ["line", "nine", "pine", "vine", "bike", "hike", "lime", "time"],
      extraWords: [
        // -ine words
        "dine",
        "fine",
        "mine",
        "wine",
        "vine",

        // -ike words
        "bike",
        "hike",
        "like",
        "mike",
        "pike",

        // Other long 'i' words
        "ride",
        "hide",
        "time",
        "mile",
        "pile",
        "tile",
        "dire",
        "fire",
        "wire",
        "ripe",
        "side",
        "wide",
        "life",
        "wise",
        "nice",
      ],
    },
    unit4: {
      targetSound: "Long Vowel i",
      words: ["hide", "ride", "pipe", "wipe", "bite", "kite", "dive", "five"],
      extraWords: [
        // -ide words
        "wide",
        "side",
        "ride",
        "tide",

        // -ite words
        "site",
        "kite",
        "mite",
        "bite",

        // Other long 'i' words
        "fine",
        "line",
        "mile",
        "pile",
        "tile",
        "wire",
        "fire",
        "dire",
        "nice",
        "wise",
        "mice",
        "rice",
        "lice",
        "vice",
        "pine",
      ],
    },
    unit5: {
      targetSound: "Long Vowel o",
      words: ["hose", "nose", "pose", "rose", "hope", "rope", "note", "vote"],
      extraWords: [
        // -ose words
        "dose",
        "lose",
        "dose",
        "gose",
        "cose",

        // -ote words
        "tote",
        "mote",
        "rote",
        "sote",
        "wote",

        // Other long 'o' words
        "home",
        "hole",
        "code",
        "mole",
        "bone",
        "tone",
        "bore",
        "core",
        "more",
        "fore",
        "gore",
      ],
    },
    unit6: {
      targetSound: "Long Vowel o",
      words: ["hole", "mole", "pole", "sole", "dome", "home", "bone", "cone"],
      extraWords: [
        // -ole words
        "dole",
        "role",
        "dole",
        "vole",
        "tole",
        "bole",

        // -ome words
        "nome",
        "rome",
        "tome",

        // Other long 'o' words
        "rode",
        "code",
        "hope",
        "core",
        "more",
        "bore",
        "gore",
        "lore",
        "fore",
        "wore",
        "hose",
        "nose",
        "pose",
        "dose",
        "rose",
      ],
    },
    unit7: {
      targetSound: "Long Vowel u",
      words: ["cube", "tube", "cute", "mute", "mule", "dune", "June", "tune"],
      extraWords: [
        // -ube words
        "lube",
        "rube",
        "dube",
        "fube",
        "kube",

        // -ute words
        "dute",
        "lute",
        "rute",
        "sute",
        "tute",

        // Other long 'u' words
        "jute",
        "rude",
        "huge",
        "pure",
        "sure",
        "lure",
        "duke",
        "buke",
        "nuke",
        "rule",
      ],
    },
  },
  level4: {
    unit1: {
      targetSound: "bl, cl, fl",
      words: [
        "black",
        "blade",
        "blimp",
        "blue",
        "clam",
        "clap",
        "cliff",
        "clock",
        "flag",
        "flame",
        "flap",
        "flute",
      ],
      extraWords: [
        "blend",
        "blunt",
        "block",
        "blink",
        "blast",
        "clap",
        "cling",
        "clip",
        "clump",
        "clan",
        "flap",
        "flip",
        "fling",
        "flint",
        "flick",
        "blip",
        "blank",
        "blink",
        "click",
        "cleft",
        "flat",
        "flex",
        "flake",
        "flame",
        "flute",
      ],
    },
    unit2: {
      targetSound: "br, cr, fr",
      words: [
        "brake",
        "brave",
        "brick",
        "bride",
        "crab",
        "crane",
        "crib",
        "cross",
        "frame",
        "frog",
        "front",
        "frost",
      ],
      extraWords: [
        "bring",
        "brink",
        "brag",
        "brisk",
        "crack",
        "crank",
        "crisp",
        "crust",
        "craft",
        "frog",
        "frisk",
        "frump",
        "frank",
        "brand",
        "brick",
        "brim",
        "crab",
        "crest",
        "fret",
        "frill",
        "fringe",
        "crap",
        "crumb",
      ],
    },
    unit3: {
      targetSound: "gl, pl, sl",
      words: [
        "glass",
        "globe",
        "glove",
        "glue",
        "plane",
        "plant",
        "plate",
        "plum",
        "sled",
        "slice",
        "slide",
        "slim",
      ],
      extraWords: [
        "glint",
        "glad",
        "gland",
        "glum",
        "glib",
        "plum",
        "plank",
        "plump",
        "plus",
        "slab",
        "slap",
        "slump",
        "slit",
        "slug",
        "glass",
        "glide",
        "plan",
        "plot",
        "plug",
        "slim",
        "slick",
        "slope",
        "sling",
        "slip",
      ],
    },
    unit4: {
      targetSound: "dr, pr, tr",
      words: [
        "dragon",
        "dress",
        "drive",
        "drum",
        "press",
        "price",
        "print",
        "prize",
        "trace",
        "track",
        "truck",
        "trumpet",
      ],
      extraWords: [
        "drip",
        "drug",
        "drank",
        "drunk",
        "draft",
        "prank",
        "prep",
        "prim",
        "print",
        "prop",
        "trap",
        "trek",
        "trim",
        "trunk",
        "trump",
        "drop",
        "drink",
        "drum",
        "prance",
        "prune",
        "trick",
        "track",
        "trot",
        "trip",
        "trade",
      ],
    },
    unit5: {
      targetSound: "sm, sn, st, sw",
      words: [
        "smell",
        "smile",
        "smoke",
        "snack",
        "snake",
        "snore",
        "stone",
        "stop",
        "stove",
        "sweet",
        "swim",
        "swing",
      ],
      extraWords: [
        "smack",
        "smog",
        "smug",
        "snap",
        "snip",
        "snub",
        "snug",
        "sniff",
        "stack",
        "step",
        "stick",
        "stump",
        "strip",
        "swam",
        "swell",
        "swift",
        "swung",
        "swipe",
        "stamp",
        "sting",
        "stunt",
        "stuff",
      ],
    },
    unit6: {
      targetSound: "ng, nk",
      words: [
        "bang",
        "fang",
        "king",
        "ring",
        "gong",
        "song",
        "bank",
        "tank",
        "pink",
        "wink",
        "dunk",
        "junk",
      ],
      extraWords: [
        "lung",
        "rang",
        "ring",
        "sung",
        "string",
        "blink",
        "drink",
        "link",
        "sink",
        "think",
        "hang",
        "long",
        "sing",
        "sting",
        "spring",
        "blank",
        "drunk",
        "plank",
        "skunk",
        "bring",
        "cling",
        "fling",
        "sling",
        "swing",
      ],
    },
    unit7: {
      targetSound: "sh, ch",
      words: [
        "shape",
        "ship",
        "shop",
        "brush",
        "fish",
        "flash",
        "cherry",
        "chick",
        "chin",
        "bench",
        "branch",
        "catch",
      ],
      extraWords: [
        "shed",
        "shell",
        "shift",
        "shut",
        "shine",
        "chest",
        "chick",
        "chunk",
        "chin",
        "chip",
        "shock",
        "shack",
        "shake",
        "shim",
        "shop",
        "check",
        "chalk",
        "champ",
        "chase",
        "chuck",
        "shelf",
        "shrub",
        "shrug",
        "chum",
        "chart",
      ],
    },
    unit8: {
      targetSound: "th, wh",
      words: [
        "thick",
        "thin",
        "thumb",
        "bath",
        "math",
        "teeth",
        "whale",
        "wheel",
        "whip",
        "whisk",
        "whisper",
        "white",
      ],
      extraWords: [
        "then",
        "thing",
        "think",
        "thud",
        "thumb",
        "whack",
        "whim",
        "whiff",
        "when",
        "whip",
        "third",
        "thrift",
        "thrill",
        "thrift",
        "thrash",
        "whisk",
        "whine",
        "whit",
        "while",
        "whiz",
        "theft",
        "thank",
        "thump",
        "whelp",
        "whence",
      ],
    },
  },
  level5: {
    unit1: {
      targetSound: "ee, ea",
      words: [
        "bee",
        "feet",
        "green",
        "peel",
        "seed",
        "tree",
        "leaf",
        "meat",
        "peanut",
        "sea",
        "seal",
        "tea",
      ],
      extraWords: [
        // ee words
        "seek",
        "week",
        "deep",
        "keep",
        "peep",
        "feel",
        "heel",
        "meet",
        "need",
        "seed",
        "seen",
        "seem",
        "teeth",
        "weed",
        "feed",
        // ea words
        "beam",
        "beat",
        "heat",
        "lead",
        "mean",
        "peak",
        "read",
        "seat",
        "team",
        "weak",
      ],
    },
    unit2: {
      targetSound: "oa, ow",
      words: [
        "boat",
        "coat",
        "goat",
        "road",
        "soap",
        "toast",
        "blow",
        "bowl",
        "pillow",
        "snow",
        "window",
        "yellow",
      ],
      extraWords: [
        // oa words
        "load",
        "toad",
        "foam",
        "loan",
        "moan",
        "oak",
        "roar",
        "soak",
        "goal",
        "roam",
        "roar",
        "groan",
        "float",
        "coach",
        "loaf",
        // ow words
        "crow",
        "flow",
        "glow",
        "grow",
        "low",
        "mow",
        "row",
        "show",
        "slow",
        "throw",
      ],
    },
    unit3: {
      targetSound: "ai, ay",
      words: [
        "mail",
        "nail",
        "rail",
        "rain",
        "tail",
        "train",
        "clay",
        "gray",
        "hay",
        "play",
        "pray",
        "tray",
      ],
      extraWords: [
        // ai words
        "aim",
        "bait",
        "gain",
        "hail",
        "main",
        "paid",
        "pain",
        "sail",
        "wait",
        "chain",
        "faint",
        "paint",
        "stain",
        "brain",
        "plain",
        // ay words
        "bay",
        "day",
        "jay",
        "may",
        "pay",
        "ray",
        "say",
        "stay",
        "way",
        "sway",
      ],
    },
    unit4: {
      targetSound: "oi, oy",
      words: [
        "boil",
        "coil",
        "coin",
        "foil",
        "oil",
        "point",
        "soil",
        "toilet",
        "boy",
        "joy",
        "soybean",
        "toy",
      ],
      extraWords: [
        // oi words
        "join",
        "void",
        "voice",
        "choice",
        "noise",
        "moist",
        "hoist",
        "joint",
        "point",
        "spoil",
        "broil",
        "loin",
        "groin",
        "coin",
        "toil",
        // oy words
        "Roy",
        "soy",
        "coy",
        "Troy",
        "ploy",
        "toy",
        "joy",
        "cloy",
        "troy",
        "void",
      ],
    },
    unit5: {
      targetSound: "ow, ou",
      words: [
        "brown",
        "clown",
        "cow",
        "crown",
        "gown",
        "owl",
        "blouse",
        "cloud",
        "count",
        "house",
        "mouse",
        "mouth",
      ],
      extraWords: [
        // ow words
        "bow",
        "dow",
        "how",
        "now",
        "pow",
        "sow",
        "vow",
        "wow",
        "fowl",
        "howl",
        "down",
        "town",
        "frown",
        "crowd",
        "prowl",
        // ou words
        "loud",
        "proud",
        "sound",
        "pound",
        "round",
        "found",
        "bound",
        "ground",
        "mount",
        "count",
      ],
    },
    unit6: {
      targetSound: "ir, er, ur",
      words: [
        "bird",
        "girl",
        "shirt",
        "skirt",
        "letter",
        "singer",
        "soccer",
        "teacher",
        "nurse",
        "purple",
        "purse",
        "turtle",
      ],
      extraWords: [
        // ir words
        "dirt",
        "firm",
        "first",
        "stir",
        "swirl",
        // er words
        "her",
        "term",
        "verb",
        "herd",
        "perk",
        "jerk",
        "perch",
        "serve",
        "stern",
        "clerk",
        // ur words
        "burn",
        "curl",
        "hurt",
        "surf",
        "turn",
        "fur",
        "burp",
        "curl",
        "blur",
        "spur",
      ],
    },
    unit7: {
      targetSound: "ar, or",
      words: [
        "arm",
        "car",
        "card",
        "farmer",
        "park",
        "star",
        "cork",
        "corn",
        "fork",
        "horse",
        "north",
        "store",
      ],
      extraWords: [
        // ar words
        "bar",
        "far",
        "jar",
        "mar",
        "tar",
        "art",
        "bark",
        "cart",
        "dark",
        "farm",
        "hard",
        "mark",
        "part",
        "yard",
        "start",
        // or words
        "for",
        "nor",
        "port",
        "sort",
        "sport",
        "torch",
        "born",
        "form",
        "fort",
        "port",
      ],
    },
    unit8: {
      targetSound: "oo",
      words: [
        "book",
        "cook",
        "foot",
        "hook",
        "look",
        "wood",
        "food",
        "goose",
        "moon",
        "pool",
        "spoon",
        "zoo",
      ],
      extraWords: [
        // short oo words
        "good",
        "hood",
        "soot",
        "wool",
        "brook",
        "took",
        "shook",
        "stood",
        "cook",
        "hook",
        "foot",
        // long oo words
        "cool",
        "fool",
        "pool",
        "root",
        "soon",
        "tool",
        "boom",
        "doom",
        "loom",
        "zoom",
        "roof",
        "room",
        "boot"
      ],
    },
  },
}
