const smartPhonicsWordBank = {
  level1: {
    unit1: {
      targetSound: "ABC",
      words: ["A", "a", "B", "b", "C", "c"],
    },
    unit2: {
      targetSound: "DEF",
      words: ["D", "d", "E", "e", "F", "f"],
    },
    unit3: {
      targetSound: "GHI",
      words: ["G", "g", "H", "h", "I", "i"],
    },
    unit4: {
      targetSound: "JKL",
      words: ["J", "j", "K", "k", "L", "l"],
    },
    unit5: {
      targetSound: "MNO",
      words: ["M", "m", "N", "n", "O", "o"],
    },
    unit6: {
      targetSound: "PQR",
      words: ["P", "p", "Q", "q", "R", "r"],
    },
    unit7: {
      targetSound: "STUV",
      words: ["S", "s", "T", "t", "U", "u", "V", "v"],
    },
    unit8: {
      targetSound: "WXYZ",
      words: ["W", "w", "X", "x", "Y", "y", "Z", "z"],
    },
  },
  level2: {
    unit1: {
      targetSound: "Short Vowel a",
      words: ["dam", "ham", "jam", "ram", "cap", "lap", "map", "nap"],
      extraWords: [
        // -am words
        "bam",
        "cam",
        "fam",
        "gam",
        "sam",

        // -ap words
        "tap",
        "zap",
        "gap",
        "rap",
        "sap",

        // Other -a words with different endings
        "bad",
        "bag",
        "gas",
        "cab",
        "dad",
        "sad",
        "tag",
        "wag",
        "max",
        "pad",
        "rad",
        "sag",
        "fab",
        "lab",
        "ban",
      ],
    },
    unit2: {
      targetSound: "Short Vowel a",
      words: ["can", "fan", "man", "pan", "bat", "cat", "hat", "mat"],
      extraWords: [
        // -an words
        "ban",
        "dan",
        "ran",
        "tan",
        "van",

        // -at words
        "sat",
        "rat",
        "pat",
        "fat",
        "lat",

        // Other short 'a' words
        "bad",
        "gab",
        "bag",
        "sad",
        "wag",
        "pad",
        "rag",
        "dad",
        "sag",
        "gas",
        "lab",
        "cab",
        "mad",
        "nag",
        "tag",
      ],
    },
    unit3: {
      targetSound: "Short Vowel e",
      words: ["jet", "net", "vet", "wet", "bed", "red", "hen", "pen"],
      extraWords: [
        // -et words
        "bet",
        "get",
        "let",
        "met",
        "set",

        // -ed words
        "fed",
        "led",
        "wed",
        "Ted",
        "med",

        // Other short 'e' words
        "leg",
        "peg",
        "beg",
        "den",
        "men",
        "ten",
        "yes",
        "end",
        "web",
        "rem",
        "hex",
        "gel",
        "hem",
        "gem",
        "bel",
      ],
    },
    unit4: {
      targetSound: "Short Vowel i",
      words: ["bib", "rib", "kid", "lid", "pig", "wig", "fin", "pin"],
      extraWords: [
        // -ib words
        "fib",
        "lib",
        "gib",

        // -id words
        "bid",
        "did",
        "mid",

        // Other short 'i' words
        "big",
        "dig",
        "fig",
        "rig",
        "jig",
        "gin",
        "win",
        "sin",
        "tin",
        "bin",
        "tip",
        "dip",
        "sip",
        "zip",
        "rip",
      ],
    },
    unit5: {
      targetSound: "Short Vowel i",
      words: ["dip", "hip", "lip", "rip", "hit", "sit", "mix", "six"],
      extraWords: [
        // -ip words
        "tip",
        "nip",
        "sip",

        // -it words
        "pit",
        "bit",
        "fit",

        // Other short 'i' words
        "wig",
        "pig",
        "dig",
        "rig",
        "gig",
        "lid",
        "rid",
        "kid",
        "did",
        "bid",
        "pin",
        "sin",
        "tin",
        "win",
        "gin",
      ],
    },
    unit6: {
      targetSound: "Short Vowel o",
      words: ["hot", "pot", "box", "fox", "cop", "hop", "dog", "log"],
      extraWords: [
        // -ot words
        "dot",
        "got",
        "lot",
        "cot",
        "tot",

        // -op words
        "bop",
        "mop",
        "top",
        "hop",
        "pop",

        // Other short 'o' words
        "bog",
        "fog",
        "jog",
        "hog",
        "dog",
        "mob",
        "rob",
        "sob",
        "cod",
        "pod",
        "nod",
        "odd",
        "bob",
        "job",
        "god",
      ],
    },
    unit7: {
      targetSound: "Short Vowel u",
      words: ["bug", "hug", "mug", "rug", "rub", "tub", "cup", "pup"],
      extraWords: [
        // -ug words
        "dug",
        "lug",
        "tug",
        "jug",
        "zug",

        // -ub words
        "cub",
        "hub",
        "sub",
        "nub",

        // Other short 'u' words
        "fun",
        "run",
        "sun",
        "gun",
        "bun",
        "cut",
        "nut",
        "put",
        "gut",
        "hut",
        "mud",
        "sud",
        "bud",
        "dud",
        "lud",
      ],
    },
    unit8: {
      targetSound: "Short Vowel u",
      words: ["bun", "fun", "run", "sun", "bud", "mud", "cut", "nut"],
      extraWords: [
        // -un words
        "gun",
        "hun",
        "pun",
        "nun",
        "tun",

        // -ud words
        "cud",
        "sud",
        "dud",
        "fud",

        // Other short 'u' words
        "bug",
        "dug",
        "hug",
        "lug",
        "mug",
        "cup",
        "pup",
        "tup",
        "sup",
        "rub",
        "tub",
        "hub",
        "rug",
        "jug",
        "nug",
      ],
    },
  },
  level3: {
    unit1: {
      targetSound: "Long Vowel a",
      words: ["bake", "cake", "lake", "rake", "cape", "tape", "cave", "wave"],
      extraWords: [
        // -ake words
        "make",
        "take",
        "bake",
        "wake",
        "sake",

        // -ave words
        "save",
        "gave",
        "wave",
        "rave",
        "pave",

        // Other long 'a' words
        "late",
        "gate",
        "mane",
        "pale",
        "sale",
        "tale",
        "lace",
        "dare",
        "care",
        "hale",
        "male",
        "fade",
        "race",
        "pace",
        "stare",
      ],
    },
    unit2: {
      targetSound: "Long Vowel a",
      words: ["game", "name", "date", "gate", "cane", "mane", "case", "vase"],
      extraWords: [
        // -ame words
        "fame",
        "tame",
        "came",
        "same",
        "lame",

        // -ate words
        "hate",
        "rate",
        "mate",
        "fate",
        "sate",

        // Other long 'a' words
        "lane",
        "care",
        "daze",
        "gaze",
        "haze",
        "pale",
        "tale",
        "sale",
        "male",
        "dare",
        "mare",
        "sane",
        "cage",
        "page",
      ],
    },
    unit3: {
      targetSound: "Long Vowel i",
      words: ["line", "nine", "pine", "vine", "bike", "hike", "lime", "time"],
      extraWords: [
        // -ine words
        "dine",
        "fine",
        "mine",
        "wine",
        "vine",

        // -ike words
        "bike",
        "hike",
        "like",
        "mike",
        "pike",

        // Other long 'i' words
        "ride",
        "hide",
        "time",
        "mile",
        "pile",
        "tile",
        "dire",
        "fire",
        "wire",
        "ripe",
        "side",
        "wide",
        "life",
        "wise",
        "nice",
      ],
    },
    unit4: {
      targetSound: "Long Vowel i",
      words: ["hide", "ride", "pipe", "wipe", "bite", "kite", "dive", "five"],
      extraWords: [
        // -ide words
        "wide",
        "side",
        "ride",
        "tide",

        // -ite words
        "site",
        "kite",
        "mite",
        "bite",

        // Other long 'i' words
        "fine",
        "line",
        "mile",
        "pile",
        "tile",
        "wire",
        "fire",
        "dire",
        "nice",
        "wise",
        "mice",
        "rice",
        "lice",
        "vice",
        "pine",
      ],
    },
    unit5: {
      targetSound: "Long Vowel o",
      words: ["hose", "nose", "pose", "rose", "hope", "rope", "note", "vote"],
      extraWords: [
        // -ose words
        "rose",
        "hose",
        "pose",
        "nose",
        "dose",

        // -ote words
        "note",
        "vote",
        "tote",
        "mote",
        "rote",

        // Other long 'o' words
        "home",
        "rope",
        "hope",
        "hole",
        "code",
        "mole",
        "bone",
        "tone",
        "bore",
        "core",
        "more",
        "fore",
        "gore",
      ],
    },
    unit6: {
      targetSound: "Long Vowel o",
      words: ["hole", "mole", "pole", "sole", "dome", "home", "bone", "cone"],
      extraWords: [
        // -ole words
        "mole",
        "pole",
        "sole",
        "hole",
        "dole",

        // -ome words
        "home",
        "dome",
        "nome",
        "rome",
        "some",

        // Other long 'o' words
        "rode",
        "code",
        "hope",
        "core",
        "more",
        "bore",
        "gore",
        "lore",
        "fore",
        "wore",
        "hose",
        "nose",
        "pose",
        "dose",
        "rose",
      ],
    },
    unit7: {
      targetSound: "Long Vowel u",
      words: ["cube", "tube", "cute", "mute", "mule", "dune", "June", "tune"],
      extraWords: [
        // -ube words
        "cube",
        "tube",
        "lube",
        "rube",
        "dube",

        // -ute words
        "cute",
        "mute",
        "dute",
        "lute",
        "rute",

        // Other long 'u' words
        "tune",
        "dune",
        "jute",
        "rude",
        "nude",
        "huge",
        "pure",
        "sure",
        "lure",
        "mule",
        "duke",
        "buke",
        "nuke",
        "rule",
        "mute",
      ],
    },
  },
  level4: {
    unit1: {
      targetSound: "bl, cl, fl",
      words: [
        "black",
        "blade",
        "blimp",
        "blue",
        "clam",
        "clap",
        "cliff",
        "clock",
        "flag",
        "flame",
        "flap",
        "flute",
      ],
    },
    unit2: {
      targetSound: "br, cr, fr",
      words: [
        "brake",
        "brave",
        "brick",
        "bride",
        "crab",
        "crane",
        "crib",
        "cross",
        "frame",
        "frog",
        "front",
        "frost",
      ],
    },
    unit3: {
      targetSound: "gl, pl, sl",
      words: [
        "glass",
        "globe",
        "glove",
        "glue",
        "plane",
        "plant",
        "plate",
        "plum",
        "sled",
        "slice",
        "slide",
        "slim",
      ],
    },
    unit4: {
      targetSound: "dr, pr, tr",
      words: [
        "dragon",
        "dress",
        "drive",
        "drum",
        "press",
        "price",
        "print",
        "prize",
        "trace",
        "track",
        "truck",
        "trumpet",
      ],
    },
    unit5: {
      targetSound: "sm, sn, st, sw",
      words: [
        "smell",
        "smile",
        "smoke",
        "snack",
        "snake",
        "snore",
        "stone",
        "stop",
        "stove",
        "sweet",
        "swim",
        "swing",
      ],
    },
    unit6: {
      targetSound: "ng, nk",
      words: [
        "bang",
        "fang",
        "king",
        "ring",
        "gong",
        "song",
        "bank",
        "tank",
        "pink",
        "wink",
        "dunk",
        "junk",
      ],
    },
    unit7: {
      targetSound: "sh, ch",
      words: [
        "shape",
        "ship",
        "shop",
        "brush",
        "fish",
        "flash",
        "cherry",
        "chick",
        "chin",
        "bench",
        "branch",
        "catch",
      ],
    },
    unit8: {
      targetSound: "th, wh",
      words: [
        "thick",
        "thin",
        "thumb",
        "bath",
        "math",
        "teeth",
        "whale",
        "wheel",
        "whip",
        "whisk",
        "whisper",
        "white",
      ],
    },
  },
  level5: {
    unit1: {
      targetSound: "ee, ea",
      words: [
        "bee",
        "feet",
        "green",
        "peel",
        "seed",
        "tree",
        "leaf",
        "meat",
        "peanut",
        "sea",
        "seal",
        "tea",
      ],
    },
    unit2: {
      targetSound: "oa, ow",
      words: [
        "boat",
        "coat",
        "goat",
        "road",
        "soap",
        "toast",
        "blow",
        "bowl",
        "pillow",
        "snow",
        "window",
        "yellow",
      ],
    },
    unit3: {
      targetSound: "ai, ay",
      words: [
        "mail",
        "nail",
        "rail",
        "rain",
        "tail",
        "train",
        "clay",
        "gray",
        "hay",
        "play",
        "pray",
        "tray",
      ],
    },
    unit4: {
      targetSound: "oi, oy",
      words: [
        "boil",
        "coil",
        "coin",
        "foil",
        "oil",
        "point",
        "soil",
        "toilet",
        "boy",
        "joy",
        "soybean",
        "toy",
      ],
    },
    unit5: {
      targetSound: "ow, ou",
      words: [
        "brown",
        "clown",
        "cow",
        "crown",
        "gown",
        "owl",
        "blouse",
        "cloud",
        "count",
        "house",
        "mouse",
        "mouth",
      ],
    },
    unit6: {
      targetSound: "ir, er, ur",
      words: [
        "bird",
        "girl",
        "shirt",
        "skirt",
        "letter",
        "singer",
        "soccer",
        "teacher",
        "nurse",
        "purple",
        "purse",
        "turtle",
      ],
    },
    unit7: {
      targetSound: "ar, or",
      words: [
        "arm",
        "car",
        "card",
        "farmer",
        "park",
        "star",
        "cork",
        "corn",
        "fork",
        "horse",
        "north",
        "store",
      ],
    },
    unit8: {
      targetSound: "oo",
      words: [
        "book",
        "cook",
        "foot",
        "hook",
        "look",
        "wood",
        "food",
        "goose",
        "moon",
        "pool",
        "spoon",
        "zoo",
      ],
    },
  },
}
